server:
  port: 8080

spring:
  application:
    name: portfolio-tracker

  datasource:
    url: jdbc:postgresql://switchyard.proxy.rlwy.net:18321/railway
    username: postgres
    password: mpZcAXPuStpwVQWclOrwfsuZRoHDIYqW
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
alpha-vantage:
  api-key: demo
  base-url: https://www.alphavantage.co/query

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.portfolio: DEBUG
    org.springframework.security: DEBUG
