spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/portfolio_db
    username: portfolio_user
    password: portfolio_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
